version: "3.8"

services:

  spark-master:
    image: bitnami/spark:3.0.0
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: bitnami/spark:3.0.0
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
    volumes:
      - ./data:/opt/data

  spark-app:
#    build: ./
    image: bitnami/spark:3.0.0
    command: ["./bin/spark-submit", "/opt/app/app.py"]
    depends_on:
      - spark-master
    environment:
      DATA_PATH: /opt/data
      SOURCE_FILE: freebase-head-1000000
      DESTINATION_FILE: out.jsonl
    volumes:
      - ./app:/opt/app
      - ./data:/opt/data
